import esbuild from 'esbuild';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        // Loaded at runtime on desktop only. A new Node module used by the plugin or a dependency fails the build
        // here instead of being bundled silently.
        '@electron/remote',
        'buffer',
        'fs',
        'os',
        'path',
    ],
    format: 'cjs',
    target: 'es2022',
    // Obsidian loads plugins as CommonJS, where a native import() of 'electron' or 'fs' cannot resolve;
    // this turns the desktop-only dynamic imports into require() calls.
    supported: { 'dynamic-import': false },
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: 'main.js',
    minify: prod,
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
